version: '3.8'

services:
  functions:
    build: .
    ports:
      - "7071:80"  # Functions host
    env_file:
      - .env
    environment:
      - FUNCTIONS_WORKER_RUNTIME=python
      - AZURE_FUNCTIONS_ENVIRONMENT=Development
      - AzureWebJobsFeatureFlags=EnableWorkerIndexing
    depends_on:
      - mongodb
    networks:
      - dashboard-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge

volumes:
  mongodb_data:
