WEATHER_ZIP_CODE= 43017
SUBREDDIT_LIST = ["watches", "collegebasketball", "nostalgia", "movies", "aww"]
NEWS_URL = 'https://news.mit.edu/topic/artificial-intelligence2'
KEYWORDS = ['generative', 'artificial intelligence', 'deep learning', 'machine learning', 'ai', 'network']
AI_NEWS_BASE_URL = "https://news.mit.edu"
LAT=40.1157
LON=-83.1327
WEATHER_BASE_URL = "https://api.openweathermap.org/data/2.5/forecast"
TRAILER_CHANNEL_IDS = ["UCi8e0iOVk1fEOogdfu4YgfA","UCLyYEq4ODlw3OD9qhGqwimw"]
ALBUM_LIMIT=30
ALBUM_URL="https://www.metacritic.com/browse/albums/release-date/available/date"
